name: Build

on: [push, pull_request]

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Setup | Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup | Toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: nightly-2024-08-20
                  components: rust-src

            - name: Setup | GCC
              uses: carlosperate/arm-none-eabi-gcc-action@v1

            - name: Check
              run: cargo check
